[project]
name = "vectordb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.0.13",
    "numpy>=2.3.1",
    "ollama>=0.5.1",
    "openai>=1.90.0",
    "pandas>=2.3.0",
    "wget>=3.2",
]
